version: '2.1'

services:
  mssqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    entrypoint: /bin/bash

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      - ./:/usr/src/app
    deploy:
      resources:
        limits:
          memory: 4g
    working_dir: /usr/src/app
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Timetrack@2023!
    volumes_from:
      - mssqldata
    networks:
      - time_track

networks:
  time_track:
    driver: bridge